services:
  kurtama-server:
    build:
      .
    ports:
      - "8007:8007"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://kurtama-db:5432/kurtama
      SPRING_DATASOURCE_USERNAME: kurtama
      SPRING_DATASOURCE_PASSWORD: kurtama
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - kurtama-db
    networks:
      - kurtama-network
  kurtama-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: kurtama
      POSTGRES_PASSWORD: kurtama
      POSTGRES_DB: kurtama
    ports:
      - "5432:5432"
    networks:
      - kurtama-network

networks:
  kurtama-network:
