kurtama.server.netty.port=8007
kurtama.server.netty.enable=true
server.port=8008
spring.datasource.url=jdbc:h2:mem:memorydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
management.endpoints.web.exposure.include=metrics,health,info,prometheus
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/monitoring
kurtama.monitoring.password=pr0m3th3us