kurtama.server.netty.port=8007
kurtama.server.netty.enable=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/kurtama
spring.datasource.username=kurtama
spring.datasource.password=kurtama
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true