logging.level.root=DEBUG
logging.level.org.schlunzis.kurtama=DEBUG
logging.level.sun.rmi=INFO
logging.level.javax.management.remote.rmi=INFO
logging.level.org.hibernate=INFO
logging.level.org.springframework=INFO
logging.level.org.thymeleaf=INFO