name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: ["bug"]
projects: ["schlunzis/1"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug.
      placeholder: Description
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: List the steps to reproduce the bug.
      placeholder: Steps
      value: "1. Go to..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: Describe the expected behaviour after the steps above.
      placeholder: Expected behaviour
      value: "It should work!"
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behaviour
      description: Describe the actual behaviour after the steps above.
      placeholder: Actual behaviour
      value: "It does not work!"
    validations:
      required: true
  - type: textarea
    id: further-information
    attributes:
      label: Further Information
      description: Do you have any further information?
      placeholder: Further Information
      value: "nothing"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0-SNAPSHOT
      default: 0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What OS are you using
      multiple: false
      options:
        - Ubuntu
        - NixOS
        - Other Linux Distribution
        - Windows
        - MacOS
      default: 0
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
