name: Feature Request
description: Submit a feature request
title: "[Feature Request]: "
labels: [ "enhancement" ]
projects: [ "schlunzis/1" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the feature request.
  - type: textarea
    id: description
    attributes:
      label: What should be implemented?
      description: Describe the feature.
      placeholder: Description
    validations:
      required: true
