#!/bin/sh

set -e

echo "Running postrm for kurtama-client with $1"
if [ "$1" = 'remove' ]; then
  # remove the installation folder
  rm -r /opt/kurtama-client/
  # remove the link in /bin
  rm /bin/kurtama-client
fi

exit 0
