#!/bin/sh

set -e

echo "Running postinst for kurtama-client with $1"
if  [ "$1" = configure ]; then
  # creating a desktop item
  xdg-desktop-menu install /opt/kurtama-client/lib/kurtama-client-Kurtama.desktop
  # creating a link, so the application can be called from the command line
  ln -sf /opt/kurtama-client/bin/Kurtama /bin/kurtama-client
fi

exit 0
