name: Build all targets

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      version:
        required: true
        type: string
      github-release:
        required: false
        type: boolean
        default: false
      prerelease:
        required: false
        type: boolean
        default: true

jobs:
  verify:
    uses: ./.github/workflows/verify.yaml

  build-to-jar:
    needs: verify
    uses: ./.github/workflows/build-jar.yaml
    strategy:
      matrix:
        os: [
          { name: ubuntu-latest, mvn: "./mvnw", jar-file-modifier: "linux" },
          { name: windows-latest, mvn: "./mvnw.cmd", jar-file-modifier: "win" }
        ]
    with:
      os: ${{ matrix.os.name }}
      mvn: ${{ matrix.os.mvn }}
      tag: ${{ inputs.tag }}
      version: ${{ inputs.version }}
      github-release: ${{ inputs.github-release }}
      prerelease: ${{ inputs.prerelease }}
      jar-file-modifier: ${{ matrix.os.jar-file-modifier }}
    secrets: inherit

  build-with-jpackage:
    needs: verify
    uses: ./.github/workflows/build-jpackage.yaml
    with:
      tag: ${{ inputs.tag }}
      version: ${{ inputs.version }}
      github-release: ${{ inputs.github-release }}
      prerelease: ${{ inputs.prerelease }}
    secrets: inherit