name: Build jar with dependencies

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      mvn:
        required: true
        type: string
      tag:
        required: true
        type: string
      version:
        required: true
        type: string
      github-release:
        required: true
        type: boolean
      prerelease:
        required: true
        type: boolean
      jar-file-modifier:
        required: true
        type: string

jobs:
  build-to-jar:
    name: Build on ${{ inputs.os }} to jar
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4.1.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          ${{ inputs.mvn }} --batch-mode --update-snapshots clean install package

      - name: Move jar files to release folder
        shell: bash
        run: |
          mkdir release
          mv client/target/client-${{ inputs.version }}.jar release/kurtama-client-${{ inputs.version }}-${{ inputs.jar-file-modifier }}.jar
          mv server/target/server-${{ inputs.version }}.jar release/kurtama-server-${{ inputs.version }}-${{ inputs.jar-file-modifier }}.jar

      - name: Upload jars to release
        if: ${{ inputs.github-release }}
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: release/*.jar
          tag: ${{ inputs.tag }}
          commit: ${{ github.sha }}
          name: ${{ inputs.tag }}
          prerelease: ${{ inputs.prerelease }}
          allowUpdates: true