name: Build all targets

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: 0.0.1-SNAPSHOT #should be equal to the version of the maven project

jobs:
  verify:
    uses: ./.github/workflows/verify.yaml

  # Windows does not allow text in versions. See requirements:
  # https://learn.microsoft.com/en-gb/windows/win32/msi/productversion
  win-version-string:
    runs-on: ubuntu-latest
    outputs:
      winVersion: ${{ steps.step1.outputs.winVersion }}
    steps:
      - id: step1
        run: |
          winVersion=$(echo "${{ inputs.version }}" | grep -oP "\d+\.\d+\.\d+")
          echo "${winVersion}"
          echo "winVersion=${winVersion}" >> "$GITHUB_OUTPUT"

  build-to-jar:
    needs: verify
    uses: ./.github/workflows/build-jar.yaml
    strategy:
      matrix:
        os: [
          { name: ubuntu-latest, mvn: "./mvnw", jar-file-modifier: "linux" },
          { name: windows-latest, mvn: "./mvnw.cmd", jar-file-modifier: "win" }
        ]
    with:
      os: ${{ matrix.os.name }}
      mvn: ${{ matrix.os.mvn }}
      version: ${{ inputs.version }}
      jar-file-modifier: ${{ matrix.os.jar-file-modifier }}
    secrets: inherit

  build-with-jpackage:
    needs: [ verify, win-version-string ]
    uses: ./.github/workflows/build-jpackage.yaml
    with:
      version: ${{ inputs.version }}
      winVersion: ${{ needs.win-version-string.outputs.winVersion }}
    secrets: inherit