name: Build with JPackage

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      winVersion:
        required: true
        type: string

jobs:
  build-on-ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build and Package
        run: ./build-client.sh linux ${{ inputs.version }}
      - name: Upload deb to release
        uses: actions/upload-artifact@v4
        with:
          name: client-deb
          path: ./target/jpackage-out/kurtama-client_${{ inputs.version }}_amd64.deb
          retention-days: 1
          overwrite: true
          if-no-files-found: error

  build-on-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build and Package
        shell: bash
        run: |
          ./build-client.sh windows ${{ inputs.version }} ${{ inputs.winVersion }}
          mv ./target/jpackage-out/Kurtama-${{ inputs.winVersion }}.exe ./target/jpackage-out/Kurtama-${{ inputs.winVersion }}-setup.exe
      - name: Upload exe to release
        uses: actions/upload-artifact@v4
        with:
          name: client-exe
          path: ./target/jpackage-out/Kurtama-${{ inputs.winVersion }}-setup.exe
          retention-days: 1
          overwrite: true
          if-no-files-found: error