name: Build jar with dependencies

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      mvn:
        required: true
        type: string
      tag:
        required: true
        type: string
      version:
        required: true
        type: string
      github-release:
        required: true
        type: boolean
      prerelease:
        required: true
        type: boolean
      jar-file-modifier:
        required: true
        type: string

jobs:
  build-to-jar:
    name: Build on ${{ inputs.os }} to jar
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4.1.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          ${{ inputs.mvn }} --batch-mode --update-snapshots clean install package

      - name: Upload client jar to release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: client/target/client-${{ inputs.version }}.jar
          tag: ${{ inputs.tag }}
          name: ${{ inputs.tag }}
          prerelease: ${{ inputs.prerelease }}
          allowUpdates: true
      - name: Upload server jar to release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: client/target/server-${{ inputs.version }}.jar
          tag: ${{ inputs.tag }}
          name: ${{ inputs.tag }}
          prerelease: ${{ inputs.prerelease }}
          allowUpdates: true