name: dev-build all targets

on:
  push:
    branches:
      - develop

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  release:
    needs: build
    uses: ./.github/workflows/release.yaml
    with:
      tag: dev
      prerelease: true
    secrets: inherit