name: Release all targets

on:
  push:
    tags:
      - 'v*'

jobs:
  create-version-string:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: echo ${{ github.ref_name }} | cut -c 2- >> "$GITHUB_OUTPUT"
  build:
    needs: create-version-string
    uses: ./.github/workflows/build.yaml
    with:
      tag: ${{ github.ref_name }}
      version: ${{ needs.create-version-string.outputs.version }}
      winVersion: 0.0.1 #requirements: https://learn.microsoft.com/en-gb/windows/win32/msi/productversion
      github-release: true
      prerelease: false
    secrets: inherit