name: Verify Changes in Server

on:
  push:
    paths:
      - 'server'
      - 'common'
      - 'pom.xml'
      - '.github/workflows/test-server.yml'

jobs:
  verify-server:
    name: Verify with Maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          ./mvnw --projects server --also-make --batch-mode --update-snapshots test