name: Verify Project

on:
  push:
    paths:
      - '.github/workflows/verify.yml'
  workflow_call:

jobs:
  verify:
    name: verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4.1.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Verify with Maven
        run: ./mvnw --batch-mode --update-snapshots verify