name: verify client changes

# run this workflow, if a push changes a file outside the 'server' directory and some other files
on:
  push:
    paths-ignore:
      - 'server'
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - '.mailmap'
      - 'README.md'

jobs:
  verify-client:
    name: verify client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4.1.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          ./mvnw --projects client --also-make --batch-mode --update-snapshots verify